import React, { useState } from 'react';
import { X, Copy, Check, Printer, FileText } from 'lucide-react';
import { DecisionAnalysis } from '../types';

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  decision: DecisionAnalysis;
}

export const ExportModal: React.FC<ExportModalProps> = ({ isOpen, onClose, decision }) => {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const winnerOption = decision.options.find((o) => o.id === decision.verdict.recommendedOptionId);

  const generateMarkdown = (): string => {
    let md = `# Decision Brief: ${decision.title}\n\n`;
    if (decision.context) md += `**Context**: ${decision.context}\n`;
    md += `**Date**: ${new Date(decision.createdAt).toLocaleDateString()}\n\n`;

    md += `## Recommended Decision\n`;
    md += `**Selected Choice**: **${winnerOption?.title || 'Selected Option'}**\n`;
    md += `**Confidence Score**: ${decision.verdict.confidenceScore}%\n\n`;
    md += `> ${decision.verdict.oneLineSummary}\n\n`;

    md += `### Deciding Factor\n`;
    md += `${decision.verdict.pivotalFactor}\n\n`;

    md += `### Alternative Condition (When to switch)\n`;
    md += `${decision.verdict.alternativeCondition}\n\n`;

    md += `### Key Trade-offs to Accept\n`;
    decision.verdict.keyTradeoffs.forEach((to) => {
      md += `- ${to}\n`;
    });
    md += `\n`;

    md += `### Action Roadmap\n`;
    decision.verdict.actionSteps.forEach((st) => {
      md += `- **${st.timeframe}**: ${st.step}\n`;
    });
    md += `\n`;

    md += `### Risk Mitigation & Contingencies\n`;
    decision.verdict.riskMitigation.forEach((rm) => {
      md += `- **Risk**: ${rm.risk}\n  *Mitigation*: ${rm.mitigation}\n`;
    });
    md += `\n`;

    md += `## Pros & Cons Matrix\n\n`;
    decision.options.forEach((opt) => {
      const items = decision.prosAndCons[opt.id] || [];
      const pros = items.filter((i) => i.type === 'pro');
      const cons = items.filter((i) => i.type === 'con');

      md += `### ${opt.title}\n`;
      md += `**Pros:**\n`;
      pros.forEach((p) => {
        md += `- [${p.category}] ${p.point} (Impact: ${p.impact.toUpperCase()})\n`;
        if (p.caveat) md += `  *Note: ${p.caveat}*\n`;
      });
      md += `**Cons:**\n`;
      cons.forEach((c) => {
        md += `- [${c.category}] ${c.point} (Impact: ${c.impact.toUpperCase()})\n`;
        if (c.caveat) md += `  *Note: ${c.caveat}*\n`;
      });
      md += `\n`;
    });

    md += `\n---\n*Generated by The Tiebreaker*`;
    return md;
  };

  const handleCopy = async () => {
    const text = generateMarkdown();
    await navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/50 backdrop-blur-xs">
      <div 
        className="relative w-full max-w-3xl max-h-[90vh] flex flex-col rounded-2xl border border-slate-200 bg-white shadow-2xl overflow-hidden"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-center justify-between border-b border-slate-200 px-6 py-4 bg-slate-50">
          <div className="flex items-center gap-2.5">
            <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-slate-900 text-amber-400">
              <FileText className="h-4 w-4" />
            </div>
            <h2 className="text-base font-bold text-slate-900">
              Export Decision Brief
            </h2>
          </div>
          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={handleCopy}
              className="inline-flex items-center gap-1.5 rounded-lg border border-slate-300 bg-white px-3 py-1.5 text-xs font-semibold text-slate-700 shadow-2xs hover:bg-slate-50 transition-all cursor-pointer"
            >
              {copied ? (
                <>
                  <Check className="h-3.5 w-3.5 text-emerald-600" />
                  <span className="text-emerald-700">Copied!</span>
                </>
              ) : (
                <>
                  <Copy className="h-3.5 w-3.5 text-slate-500" />
                  <span>Copy Markdown</span>
                </>
              )}
            </button>
            <button
              type="button"
              onClick={handlePrint}
              className="inline-flex items-center gap-1.5 rounded-lg border border-slate-300 bg-white px-3 py-1.5 text-xs font-semibold text-slate-700 shadow-2xs hover:bg-slate-50 transition-all cursor-pointer"
            >
              <Printer className="h-3.5 w-3.5 text-slate-500" />
              <span>Print</span>
            </button>
            <button
              type="button"
              onClick={onClose}
              className="rounded-lg p-1.5 text-slate-400 hover:bg-slate-200/60 hover:text-slate-700 transition-colors"
            >
              <X className="h-5 w-5" />
            </button>
          </div>
        </div>

        <div className="flex-1 overflow-y-auto p-6 font-mono text-xs text-slate-800 bg-slate-50 select-all">
          <pre className="whitespace-pre-wrap font-sans text-slate-800 text-sm leading-relaxed font-normal">
            {generateMarkdown()}
          </pre>
        </div>

        <div className="border-t border-slate-200 bg-white px-6 py-3.5 flex items-center justify-between text-xs text-slate-500">
          <span>Ready to copy into documents, messaging, or emails.</span>
          <button
            type="button"
            onClick={onClose}
            className="rounded-lg bg-slate-900 hover:bg-slate-800 px-4 py-1.5 text-xs font-semibold text-white transition-all cursor-pointer"
          >
            Done
          </button>
        </div>
      </div>
    </div>
  );
};
